import React from 'react'

export const metadata = {
  title: "Email Campaigns | Isys",
  description: "Generated by create next app",
};

const Layout = ({children}) => {
  return (
    <div>
        {children}
    </div>
  )
}

export default Layout