import { Inter } from "next/font/google";
import "../styles/globals.css";
import ReduxProvider from "@/redux/provider";
import { GoogleOAuthProvider } from "@react-oauth/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Isys",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme='cmyk'>
      <body className={inter.className} >
        <GoogleOAuthProvider clientId="52716464133-fm49t8ujps4miljt4g1kgjd869fs242j.apps.googleusercontent.com">
        <ReduxProvider>{children}</ReduxProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
